version: '3.4'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      # interval: 10s
      # timeout: 5s
      # retries: 5

      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 20s
    volumes:
        - ${VOLUME_DIR}/db_data:/var/lib/mysql  # Add this line for the volume

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_EXTERNAL_PORT}:80
    environment:
      PMA_HOST: db
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
      # db:
      #   condition: service_healthy

  # rust-app:
  #   build:
  #     context: ./server
  #   ports:
  #     - "${SERVER_EXTERNAL_PORT}:8080"
  #   volumes:
  #     - ./server:/app
  #   depends_on:
  #     - db
  #     # db:
  #     #   condition: service_healthy