version: '3.4'

services:
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    # ports:
    #   - "5432:5432"

  rust-app:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres_user:postgres_password@postgres:5432/mydatabase"
