[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
# risc0-build = { version = "0.21.0" }
# risc0-build = { version = "1.0.1" }
risc0-build = { version = "1.0.5" }

[package.metadata.risc0]
methods = ["guest"]
