version: '3.4'

services:
  rust-app-executor:
    build:
      context: ./
    cpus: "${EXECUTOR_CPUS}"
    environment:
      program_distributor_url: ${PROGRAM_DISTRIBUTOR_URL}
    volumes:
      - executor_volume:/app
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  executor_volume: