version: '3.4'

services:
  rust-app:
    build:
      context: ./
    # ports:
    #   - "${SERVER_EXTERNAL_PORT}:8080"
    #   # - "127.0.0.1:${SERVER_EXTERNAL_PORT}:8080"
    #   # - "0.0.0.0:${SERVER_EXTERNAL_PORT}:8080"
    #   # - "0.0.0.0:${SERVER_EXTERNAL_PORT}:8080"
    # cpus: "${MY_SERVICE_CPUS}"
    tty: true
    stdin_open: true
    environment:
      database_url: "${DATABASE_URL}"

    volumes:
      # - ./program_distributor:/app
      - ./:/app
    # depends_on:
    #   - db
    #   # db:
    #   #   condition: service_healthy

    extra_hosts:
        - "host.docker.internal:host-gateway"
