[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }

risc0-zkvm = { version = "1.0.1" }

tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
bincode = "1.3.3"
csv = "1.3.0"
base64 = "0.22.0"
