[package]
name = "distcom"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13"
actix-multipart = "0.6.1"
actix-web = "4"
diesel = "2.1.4"
futures-util = "0.3.29"
lazy_static = "1.4.0"
serde = "1.0.192"
serde_derive = "1.0.192"
serde_json = "1.0.108"
tar = "0.4.40"
