[package]
name = "uploader_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.4"
serde = "1.0.202"
serde_derive = "1.0.202"
serde_json = "1.0.117"
tar = "0.4.40"
