version: '3.4'

services:
  rust-app-uploader:
    build:
      context: ./
    environment:
      program_distributor_url: ${PROGRAM_DISTRIBUTOR_URL}
    volumes:
      - uploader_volume:/app
      - ./programs_data:/app/programs_data
      - ./uploads:/app/uploads
      - ./template_methods:/app/downloads/template
    extra_hosts:
        - "host.docker.internal:host-gateway"

volumes:
  uploader_volume: