[package]
# This is where the ELF and ID method element names are defined
name = "downloaded_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
base64 = "0.22.1"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"